### ISSUE TITLE
EVERYTHING

### ISSUE THREAD

**Issue by ghost** [NotAkash/PyCasino#4]
kinda shit honestly...
just like your nose
nose long like garden hose.
But im moving that cornflakes... Rice Krispies

**Comment by ghost** [comment]
Yo, Big Shaq, the one and only
Man's not hot, never hot
Skrrat, skidi-kat-kat
Boom!

Two plus two is four, minus one that's three, quick maths
Everyday man's on the block, smoke trees
See your girl in the park, that girl is a uckers
When the ting went quack-quack-quack, you man were ducking
Hold tight, Asznee , he's got the pumpy 
Hold tight, my man, he's got the frisbee
I trap, trap, trap on the phone, movin' that cornflakes
Rice Krispies, hold tight my girl Whitney
On the road doin' ten toes, like my toes 
You man thought I froze, I see a peng girl, then I pose
If she ain't on it, I ghost, hah, look at your nose
You donut, nose long like garden hose

I tell her man's not hot, I tell her man's not hot
The girl told me, "Take off your jacket"
I said, "Babes, man's not hot"
I tell her man's not hot
I tell her man's not hot 
The girl told me, "Take off your jacket"
I said, "Babes, man's not hot"
 

Hop out the four-door with the .44, it was one, two, three and four
Chillin' in the corridor , your dad is forty-four
And he's still callin' man for a draw, let him know
When I see him, I'm gonna spin his jaw
Take man's Twix by force, send man's shop by force
Your girl knows I've got the sauce, no ketchup
Just sauce, raw sauce
Ah, yo, boom, ah

The ting goes skrrrahh, pap, pap, ka-ka-ka
Skidiki-pap-pap, and a pu-pu-pudrrrr-boom
Skya, du-du-ku-ku-dun-dun
Poom, poom, you dun know

I tell her man's not hot, I tell her man's not hot
The girl told me, "Take off your jacket"
I said, "Babes, man's not hot"
I tell her man's not hot
I tell her man's not hot
The girl told me, "Take off your jacket"
I said, "Babes, man's not hot"

Man can never be hot, perspiration ting
Lynx Effect , you didn't hear me, did you?
Use roll-on, or spray
But either way, A-B-C-D

The ting goes skrrrahh, pap, pap, ka-ka-ka
Skidiki-pap-pap, and a pu-pu-pudrrrr-boom
Skya, du-du-ku-ku-dun-dun
Poom, poom, you dun know

Big Shaq, man's not hot
I tell her man's not hot 
40 degrees and man's not hot
Yo, in the sauna, man's not hot
Yeah, skidika-pap-pap

**Comment by NotAkash** [comment]
👍 Thanks For The Review :-: 👎
